CREATE DATABASE IF NOT EXISTS JDlivros;

USE JDlivros;

CREATE TABLE IF NOT EXISTS livros (
    codigo INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    editora VARCHAR(50) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL
);
